export const types = {
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT",
  CREATE_STREAM: "CREATE_STREAM",
  GET_STREAM_LIST: "GET_STREAM_LIST",
  GET_STREAM: "GET_STREAM",
  EDIT_STREAM: "EDIT_STREAM",
  DELETE_STREAM: "DELETE_STREAM",
};
